// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: resolver.proto

package resolverv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Resolver_AddDNSServer_FullMethodName    = "/resolver.v1.Resolver/AddDNSServer"
	Resolver_DeleteDNSServer_FullMethodName = "/resolver.v1.Resolver/DeleteDNSServer"
	Resolver_GetDNSServers_FullMethodName   = "/resolver.v1.Resolver/GetDNSServers"
)

// ResolverClient is the client API for Resolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResolverClient interface {
	AddDNSServer(ctx context.Context, in *AddDNSServerRequest, opts ...grpc.CallOption) (*AddDNSServerResponse, error)
	DeleteDNSServer(ctx context.Context, in *DeleteDNSServerRequest, opts ...grpc.CallOption) (*DeleteDNSServerResponse, error)
	GetDNSServers(ctx context.Context, in *GetDNSServersRequest, opts ...grpc.CallOption) (*GetDNSServersResponse, error)
}

type resolverClient struct {
	cc grpc.ClientConnInterface
}

func NewResolverClient(cc grpc.ClientConnInterface) ResolverClient {
	return &resolverClient{cc}
}

func (c *resolverClient) AddDNSServer(ctx context.Context, in *AddDNSServerRequest, opts ...grpc.CallOption) (*AddDNSServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDNSServerResponse)
	err := c.cc.Invoke(ctx, Resolver_AddDNSServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) DeleteDNSServer(ctx context.Context, in *DeleteDNSServerRequest, opts ...grpc.CallOption) (*DeleteDNSServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDNSServerResponse)
	err := c.cc.Invoke(ctx, Resolver_DeleteDNSServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) GetDNSServers(ctx context.Context, in *GetDNSServersRequest, opts ...grpc.CallOption) (*GetDNSServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDNSServersResponse)
	err := c.cc.Invoke(ctx, Resolver_GetDNSServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResolverServer is the server API for Resolver service.
// All implementations must embed UnimplementedResolverServer
// for forward compatibility.
type ResolverServer interface {
	AddDNSServer(context.Context, *AddDNSServerRequest) (*AddDNSServerResponse, error)
	DeleteDNSServer(context.Context, *DeleteDNSServerRequest) (*DeleteDNSServerResponse, error)
	GetDNSServers(context.Context, *GetDNSServersRequest) (*GetDNSServersResponse, error)
	mustEmbedUnimplementedResolverServer()
}

// UnimplementedResolverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResolverServer struct{}

func (UnimplementedResolverServer) AddDNSServer(context.Context, *AddDNSServerRequest) (*AddDNSServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDNSServer not implemented")
}
func (UnimplementedResolverServer) DeleteDNSServer(context.Context, *DeleteDNSServerRequest) (*DeleteDNSServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDNSServer not implemented")
}
func (UnimplementedResolverServer) GetDNSServers(context.Context, *GetDNSServersRequest) (*GetDNSServersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDNSServers not implemented")
}
func (UnimplementedResolverServer) mustEmbedUnimplementedResolverServer() {}
func (UnimplementedResolverServer) testEmbeddedByValue()                  {}

// UnsafeResolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResolverServer will
// result in compilation errors.
type UnsafeResolverServer interface {
	mustEmbedUnimplementedResolverServer()
}

func RegisterResolverServer(s grpc.ServiceRegistrar, srv ResolverServer) {
	// If the following call panics, it indicates UnimplementedResolverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Resolver_ServiceDesc, srv)
}

func _Resolver_AddDNSServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDNSServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).AddDNSServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_AddDNSServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).AddDNSServer(ctx, req.(*AddDNSServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_DeleteDNSServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDNSServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).DeleteDNSServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_DeleteDNSServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).DeleteDNSServer(ctx, req.(*DeleteDNSServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_GetDNSServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDNSServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).GetDNSServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_GetDNSServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).GetDNSServers(ctx, req.(*GetDNSServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Resolver_ServiceDesc is the grpc.ServiceDesc for Resolver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Resolver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resolver.v1.Resolver",
	HandlerType: (*ResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDNSServer",
			Handler:    _Resolver_AddDNSServer_Handler,
		},
		{
			MethodName: "DeleteDNSServer",
			Handler:    _Resolver_DeleteDNSServer_Handler,
		},
		{
			MethodName: "GetDNSServers",
			Handler:    _Resolver_GetDNSServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resolver.proto",
}
