// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: resolver.proto

package resolverv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddDNSServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDNSServerRequest) Reset() {
	*x = AddDNSServerRequest{}
	mi := &file_resolver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDNSServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDNSServerRequest) ProtoMessage() {}

func (x *AddDNSServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDNSServerRequest.ProtoReflect.Descriptor instead.
func (*AddDNSServerRequest) Descriptor() ([]byte, []int) {
	return file_resolver_proto_rawDescGZIP(), []int{0}
}

func (x *AddDNSServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddDNSServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDNSServerResponse) Reset() {
	*x = AddDNSServerResponse{}
	mi := &file_resolver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDNSServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDNSServerResponse) ProtoMessage() {}

func (x *AddDNSServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDNSServerResponse.ProtoReflect.Descriptor instead.
func (*AddDNSServerResponse) Descriptor() ([]byte, []int) {
	return file_resolver_proto_rawDescGZIP(), []int{1}
}

func (x *AddDNSServerResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type DeleteDNSServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDNSServerRequest) Reset() {
	*x = DeleteDNSServerRequest{}
	mi := &file_resolver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDNSServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDNSServerRequest) ProtoMessage() {}

func (x *DeleteDNSServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDNSServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteDNSServerRequest) Descriptor() ([]byte, []int) {
	return file_resolver_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteDNSServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteDNSServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDNSServerResponse) Reset() {
	*x = DeleteDNSServerResponse{}
	mi := &file_resolver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDNSServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDNSServerResponse) ProtoMessage() {}

func (x *DeleteDNSServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDNSServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteDNSServerResponse) Descriptor() ([]byte, []int) {
	return file_resolver_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteDNSServerResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type GetDNSServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDNSServersRequest) Reset() {
	*x = GetDNSServersRequest{}
	mi := &file_resolver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDNSServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDNSServersRequest) ProtoMessage() {}

func (x *GetDNSServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDNSServersRequest.ProtoReflect.Descriptor instead.
func (*GetDNSServersRequest) Descriptor() ([]byte, []int) {
	return file_resolver_proto_rawDescGZIP(), []int{4}
}

type GetDNSServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDNSServersResponse) Reset() {
	*x = GetDNSServersResponse{}
	mi := &file_resolver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDNSServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDNSServersResponse) ProtoMessage() {}

func (x *GetDNSServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDNSServersResponse.ProtoReflect.Descriptor instead.
func (*GetDNSServersResponse) Descriptor() ([]byte, []int) {
	return file_resolver_proto_rawDescGZIP(), []int{5}
}

func (x *GetDNSServersResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_resolver_proto protoreflect.FileDescriptor

const file_resolver_proto_rawDesc = "" +
	"\n" +
	"\x0eresolver.proto\x12\vresolver.v1\")\n" +
	"\x13AddDNSServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x14AddDNSServerResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\",\n" +
	"\x16DeleteDNSServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x17DeleteDNSServerResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"\x16\n" +
	"\x14GetDNSServersRequest\"-\n" +
	"\x15GetDNSServersResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names2\x95\x02\n" +
	"\bResolver\x12S\n" +
	"\fAddDNSServer\x12 .resolver.v1.AddDNSServerRequest\x1a!.resolver.v1.AddDNSServerResponse\x12\\\n" +
	"\x0fDeleteDNSServer\x12#.resolver.v1.DeleteDNSServerRequest\x1a$.resolver.v1.DeleteDNSServerResponse\x12V\n" +
	"\rGetDNSServers\x12!.resolver.v1.GetDNSServersRequest\x1a\".resolver.v1.GetDNSServersResponseB>Z<github.com/Friend-zva/dns-application/resolver/v1;resolverv1b\x06proto3"

var (
	file_resolver_proto_rawDescOnce sync.Once
	file_resolver_proto_rawDescData []byte
)

func file_resolver_proto_rawDescGZIP() []byte {
	file_resolver_proto_rawDescOnce.Do(func() {
		file_resolver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resolver_proto_rawDesc), len(file_resolver_proto_rawDesc)))
	})
	return file_resolver_proto_rawDescData
}

var file_resolver_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_resolver_proto_goTypes = []any{
	(*AddDNSServerRequest)(nil),     // 0: resolver.v1.AddDNSServerRequest
	(*AddDNSServerResponse)(nil),    // 1: resolver.v1.AddDNSServerResponse
	(*DeleteDNSServerRequest)(nil),  // 2: resolver.v1.DeleteDNSServerRequest
	(*DeleteDNSServerResponse)(nil), // 3: resolver.v1.DeleteDNSServerResponse
	(*GetDNSServersRequest)(nil),    // 4: resolver.v1.GetDNSServersRequest
	(*GetDNSServersResponse)(nil),   // 5: resolver.v1.GetDNSServersResponse
}
var file_resolver_proto_depIdxs = []int32{
	0, // 0: resolver.v1.Resolver.AddDNSServer:input_type -> resolver.v1.AddDNSServerRequest
	2, // 1: resolver.v1.Resolver.DeleteDNSServer:input_type -> resolver.v1.DeleteDNSServerRequest
	4, // 2: resolver.v1.Resolver.GetDNSServers:input_type -> resolver.v1.GetDNSServersRequest
	1, // 3: resolver.v1.Resolver.AddDNSServer:output_type -> resolver.v1.AddDNSServerResponse
	3, // 4: resolver.v1.Resolver.DeleteDNSServer:output_type -> resolver.v1.DeleteDNSServerResponse
	5, // 5: resolver.v1.Resolver.GetDNSServers:output_type -> resolver.v1.GetDNSServersResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resolver_proto_init() }
func file_resolver_proto_init() {
	if File_resolver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resolver_proto_rawDesc), len(file_resolver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resolver_proto_goTypes,
		DependencyIndexes: file_resolver_proto_depIdxs,
		MessageInfos:      file_resolver_proto_msgTypes,
	}.Build()
	File_resolver_proto = out.File
	file_resolver_proto_goTypes = nil
	file_resolver_proto_depIdxs = nil
}
